---

- name: configure grub settings
  ansible.builtin.lineinfile:
    path: "{{ grub_file }}"
    regexp: '^.*{{ item.key }}='
    line: "{{ item.key }}={{ item.value }}"
    state: present
  loop: "{{ grub_setting }}"
  when: grub_task == "configure"
  notify: rebuild grub

- name: remove grub settings
  ansible.builtin.lineinfile:
    path: "{{ grub_file }}"
    regexp: '^.*{{ item.key }}='
    state: absent
  loop: "{{ grub_setting }}"
  when: grub_task == "remove"
  notify: rebuild grub

...
