---

- name: ensure tasks run only on selected os releases
  block:

    - name: configure grub settings
      ansible.builtin.lineinfile:
        path: "{{ grub_file }}"
        regexp: '^.*{{ item.key }}='
        line: "{{ item.key }}={{ item.value }}"
        state: present
      loop: "{{ grub_settings }}"
      loop_control:
        label: "{{ item.key }}"
      when: grub_task == "configure"
      notify:
        - rebuild grub 001
        - rebuild grub 002

    - name: remove grub settings
      ansible.builtin.lineinfile:
        path: "{{ grub_file }}"
        regexp: '^.*{{ item.key }}='
        state: absent
      loop: "{{ grub_settings }}"
      loop_control:
        label: "{{ item.key }}"
      when: grub_task == "remove"
      notify:
        - rebuild grub 001
        - rebuild grub 002

  when: >
    ansible_distribution == "Fedora" or
    ansible_distribution == "RedHat" or
    ansible_distribution == "Rocky"

...
