---

- name: ensure tasks run only on selected os releases
  block:

    - name: configure kernel arguments
      block:

        - name: configure kernel arguments
          ansible.builtin.command:
            cmd: "grubby --update-kernel=ALL --args='{{ item }}'"
          notify:
            - rebuild grub 001
            - rebuild grub 002
          register: grubby_kernel_arguments
          loop: "{{ kernel_arguments }}"

        - name: display grubby result
          ansible.builtin.debug:
            var: grubby_kernel_arguments
            verbosity: 1

      when: grubby_task == "configure"

    - name: remove kernel arguments
      block:

        - name: remove kernel arguments
          ansible.builtin.command:
            cmd: "grubby --update-kernel=ALL --remove-args='{{ item }}'"
          notify:
            - rebuild grub 001
            - rebuild grub 002
          register: grubby_kernel_arguments
          loop: "{{ kernel_arguments }}"

        - name: display grubby result
          ansible.builtin.debug:
            var: grubby_kernel_arguments
            verbosity: 1

      when: grubby_task == "remove"

  when: >
    ansible_distribution == "Fedora" or
    ansible_distribution == "Rocky"

...
